// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryFilters } from "./QueryFilters";
import type { QueryPlan } from "./QueryPlan";

export type GraphQueryParams = { limit: number | null, pool_id: string | null, token_address: string | null, filters: QueryFilters | null, query_plan: QueryPlan | null, };
