// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GraphQueryParams } from "./GraphQueryParams";
import type { GraphQueryType } from "./GraphQueryType";

export type GraphQueryInput = { protocol: string, network: string, query_type: GraphQueryType, params: GraphQueryParams | null, };
