// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphQueryType = "top_pools" | "pool_info" | "token_price" | "filtered_pools" | "query_plan";
