// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OdosAction } from "./OdosAction";

export type OdosInput = { action: OdosAction, input_token: string | null, output_token: string | null, amount: string | null, token: string | null, tokens: Array<string> | null, slippage_percent: number | null, chain_id: bigint | null, network: string | null, };
