// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaperTradingAction } from "./PaperTradingAction";

export type PaperTradingInput = { action: PaperTradingAction, input_token: string | null, output_token: string | null, input_amount: string | null, expected_output: string | null, input_price_usd: number | null, output_price_usd: number | null, chain_id: bigint | null, limit: bigint | null, };
