// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaperTradingAction = "execute_swap" | "get_balances" | "get_metrics" | "get_trades";
