// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryFilters } from "./QueryFilters";

/**
 * Query plan from inference strategist (InferQueryPlan)
 */
export type QueryPlan = { target_networks: Array<string>, target_protocols: Array<string>, data_filters: QueryFilters, query_priority: number, expected_data_points: number, };
