// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query filters for intelligent data fetching (from InferQueryPlan)
 */
export type QueryFilters = { min_tvl_usd: number | null, min_volume_tvl_ratio: number | null, token_pairs: Array<string> | null, exclude_tokens: Array<string> | null, min_volume_24h_usd: number | null, fee_tiers: Array<number> | null, };
