// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WalletAction } from "./WalletAction";

export type WalletInput = { action: WalletAction, network: string | null, chain_id: bigint | null, token_address: string | null, };
